### ISSUE TITLE
apt-get update failing

### ISSUE THREAD

**Issue by robinvandenbogaard** [AdoptOpenJDK/openjdk-build#1906] opened 2020-06-18 07:26 UTC
Following the installation guide in an docker container `apt-get update` fails after adding the repository. I'm trying to install the `adoptopenjdk-11-hotspot` package which happens to reside in the `https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main amd64 Packages`

```
apt-get update && \
    apt-get install -y wget software-properties-common apt-transport-https curl sshpass && \
    wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && \
    add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ && \
    apt-get update
```
Failes with output:
```
Hit:1 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Ign:3 http://deb.debian.org/debian stretch InRelease
Hit:4 http://deb.debian.org/debian stretch-updates InRelease
Hit:5 http://deb.debian.org/debian stretch Release
Ign:7 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch InRelease
Ign:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch Release
Ign:9 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main all Packages
Ign:10 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main amd64 Packages
Ign:9 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main all Packages
Ign:10 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main amd64 Packages
Ign:9 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main all Packages
Ign:10 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main amd64 Packages
Ign:9 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main all Packages
Ign:10 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main amd64 Packages
Ign:9 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main all Packages
Ign:10 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main amd64 Packages
Ign:9 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main all Packages
Err:10 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch/main amd64 Packages
  404  Not Found
Reading package lists... Done
W: The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Possibly related to https://github.com/AdoptOpenJDK/openjdk-build/issues/1179

**Comment by aahlenst** [comment] 2020-06-18 07:29
Duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1399.

**Closed** 2020-06-18 15:25 UTC
Labels: duplicate

**Comment by robinvandenbogaard** [comment] 2020-06-19 07:11
Works!
