### ISSUE TITLE
Time Zone updates for Java8

### ISSUE THREAD

**Issue by ed03875** [AdoptOpenJDK/openjdk-build#1090] opened 2019-05-16 20:03 UTC
Windows 10

OpenJDK J9 Java 8

I don't know where to submit this but I see a Java 11 similar problem here so I am placing this here for now. 
How does one update the TZDB.dat file for OpenJDK Java 8.   I have tried ziupdater which produces the same error with any release tzdata2018i - tzdata2019a "org.ziupdater.compiler.tzdb.DateTimeException: Invalid value for SecondOfDay value: 90000"
I have tried tzdbgen-1.0.2.jar which produces no results.
Since TZUpdator is Oracle license and specific to Oracle and JTZU is IBM specific there does not seem to be a way to update.  With  the current era change in Japan this is a significant problem 
**output from error**
[C:\openjdktimezone] C:\openjdktimezone\jdk8u202-b08\jre\bin\java  -jar C:\openjdktimezone\ziupdater\ziupdater-1.0.1.2.jar -l file:\openjdktimezone\tzdata2018i.tar.gz
Failed: java.lang.Exception: Failed while parsing file 'c:\tmp\ziupdater1480240214489042385699662236019162\srcdir\asia' on line 1842 'Rule      Japan   1948    1951    -       Sep     Sat>=8  25:00   0       S'
java.lang.Exception: Failed while parsing file 'c:\tmp\ziupdater1480240214489042385699662236019162\srcdir\asia' on line 1842 'Rule      Japan   1948    1951    -       Sep     Sat>=8  25:00   0       S'
        at org.ziupdater.compiler.tzdb.TzdbZoneRulesCompiler.parseFile(TzdbZoneRulesCompiler.java:389)
        at org.ziupdater.compiler.tzdb.TzdbZoneRulesCompiler.compile(TzdbZoneRulesCompiler.java:187)
        at org.ziupdater.compiler.tzdb.TzdbZoneRulesCompiler.main(TzdbZoneRulesCompiler.java:91)
        at org.ziupdater.compiler.tzdb.ZiupdaterCompiler.compile(ZiupdaterCompiler.java:69)
        at org.ziupdater.main.UpdateHelper.updateTzdata(UpdateHelper.java:180)
        at org.ziupdater.main.Main.updateVersion(Main.java:123)
        at org.ziupdater.main.Main.main(Main.java:140)
Caused by: org.ziupdater.compiler.tzdb.DateTimeException: Invalid value for SecondOfDay value: 90000
        at org.ziupdater.compiler.tzdb.ChronoField.checkValidValue(ChronoField.java:183)
        at org.ziupdater.compiler.tzdb.LocalTime.ofSecondOfDay(LocalTime.java:216)
        at org.ziupdater.compiler.tzdb.TzdbZoneRulesCompiler.parseMonthDayTime(TzdbZoneRulesCompiler.java:487)
        at org.ziupdater.compiler.tzdb.TzdbZoneRulesCompiler.parseRuleLine(TzdbZoneRulesCompiler.java:411)
        at org.ziupdater.compiler.tzdb.TzdbZoneRulesCompiler.parseFile(TzdbZoneRulesCompiler.java:366)
        .

**Comment by karianna** [comment] 2019-05-19 13:25
Duplicate of #1057

**Closed by karianna** 2019-05-19 13:25 UTC
Labels: duplicate
