### ISSUE TITLE
JDK-Next Windows Installer Failing

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1712] opened 2020-04-27 08:50 UTC
**Platform:**
jdk_next-windows

**Architecture:**
x64-hotspot

~https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot JDK next has [tests disabled](https://github.com/AdoptOpenJDK/openjdk-build/blob/d97d479ecdd580f202343929c64143efea18a4c3/pipelines/jobs/configurations/jdk15_pipeline_config.groovy#L36) for x64-Windows on nightlies but seems to be trying to run them anyway.~ This is an installer failure as per https://github.com/AdoptOpenJDK/openjdk-build/issues/1712#issuecomment-621933568
```
Archiving artifacts
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
Running test: false
[Pipeline] parallel
[Pipeline] { (Branch: false)
[Pipeline] stage
[Pipeline] { (false)
[Pipeline] library
Only using first definition of library openjdk-jenkins-helper
[Pipeline] echo
Requested test job that does not exist or is disabled: Test_openjdk15_hs_false_x86-64_windows
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // parallel
[Pipeline] node
Running on Jenkins in /home/jenkins/.jenkins/workspace/build-scripts/jobs/jdk/jdk-windows-x64-hotspot
[Pipeline] {
[Pipeline] stage
[Pipeline] { (installer)
[Pipeline] build (Building build-scripts » release » create_installer_windows)
Scheduling project: build-scripts » release » create_installer_windows
Starting building: build-scripts » release » create_installer_windows #3884
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
Execution error: null
[Pipeline] End of Pipeline
Finished: FAILURE
```

**Comment by M-Davies** [comment] 2020-04-27 08:54
Reran the job regenerator https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk/53/console

Will check tomorrow if it's still an issue

**Comment by M-Davies** [comment] 2020-04-27 08:59
FYI @andrew-m-leonard

**Comment by M-Davies** [comment] 2020-04-28 12:25
Build today seems alright. It failed, but was due to the sign_build job this time

**Comment by M-Davies** [comment] 2020-04-29 09:02
Still a problem https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/89/

**Comment by M-Davies** [comment] 2020-04-30 09:16
For some reason, `buildConfig.TEST_LIST` is set to `false` at [this](https://github.com/AdoptOpenJDK/openjdk-build/blob/0cae7e2e783c11631c3a2671ca1612d22c098414/pipelines/build/common/openjdk_build_pipeline.groovy#L108) point, and still tries to run tests. Adding a check to ensure only valid tests are ran, should be sufficient to fix this issue.

**Comment by karianna** [comment] 2020-04-30 12:46
The PR is a valid workaround, but should we not fix the root cause?

**Comment by M-Davies** [comment] 2020-04-30 12:52
In the interest of allowing the builds to run, this PR will work for now. Fixing the root cause would be preferable and will be the next step

**Comment by karianna** [comment] 2020-04-30 13:27
Landed the PR, reopening this issue to find root cause

**Comment by M-Davies** [comment] 2020-04-30 15:35
Looking at the passing [mac builds](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-x64-hotspot/90/), they also have this error but move past this point, implying that it's not the test list thats the problem
```
Archiving artifacts
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
Running test: false
[Pipeline] parallel
[Pipeline] { (Branch: false)
[Pipeline] stage
[Pipeline] { (false)
[Pipeline] library
Only using first definition of library openjdk-jenkins-helper
[Pipeline] echo
Requested test job that does not exist or is disabled: Test_openjdk15_hs_false_x86-64_mac
```
The issue instead could be due to the installer failing. 
```
Execution error: null
```
Will raise in slack.

**Comment by M-Davies** [comment] 2020-04-30 15:39
Ref https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1588261040169800?thread_ts=1588260983.169700&cid=C09NW3L2J, this is an installer failure. Nothing to do with the testlists pulling in the wrong information. My mistake. 
```
Build step 'Execute Windows batch command' marked build as failure
Archiving artifacts
[Slack Notifications] found #3883 as previous completed, non-aborted build
[Slack Notifications] will send OnEveryFailureNotification because build matches and user preferences allow it
Finished: FAILURE
```

Sidenote, I really hope that https://github.com/AdoptOpenJDK/openjdk-build/pull/1717 works as I keep misreading the console logs! :/

**Comment by M-Davies** [comment] 2020-04-30 15:41
Ok so it's the installer that's failing, is anyone currently triaging the installer failure jobs?

**Comment by M-Davies** [comment] 2020-04-30 15:55
@andrew-m-leonard ?

**Comment by Haroon-Khel** [comment] 2020-05-05 16:53
The latest failure, https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/3947/console (for those who have perms to see). I think the failure seems to stem from this bit in the console output. 
```
First .\SourceDir\OpenJDK15\hotspot\x64\jdk-15.0.0 not exists
Second .\SourceDir\OpenJDK15\hotspot\x64\jdk-15+21 not exists
Third .\SourceDir\OpenJDK15\hotspot\x64\jdk-15.0.0+21 not exists
SOURCE Dir not found / failed
```
which corresponds to [this](https://github.com/AdoptOpenJDK/openjdk-installer/blob/6d9ea59131b2db59ce2487962c01b9c77daf8dab/wix/Build.OpenJDK_generic.cmd#L121) in the `Build.OpenJDK_generic.cmd` script of the Installer repo

**Comment by M-Davies** [comment] 2020-05-07 07:47
I'm not that adapt with Windows scripts so you'll have to bear with me on this one.

From my understanding, the failed statements above are produced from the if statements checking if [REPRO_DIR](https://github.com/AdoptOpenJDK/openjdk-installer/blob/6d9ea59131b2db59ce2487962c01b9c77daf8dab/wix/Build.OpenJDK_generic.cmd#L93) exists and and at lines [109](https://github.com/AdoptOpenJDK/openjdk-installer/blob/6d9ea59131b2db59ce2487962c01b9c77daf8dab/wix/Build.OpenJDK_generic.cmd#L109) and [115](https://github.com/AdoptOpenJDK/openjdk-installer/blob/6d9ea59131b2db59ce2487962c01b9c77daf8dab/wix/Build.OpenJDK_generic.cmd#L115) where it alters the query again and checks again as in the console output.

@Haroon-Khel Which directory exists as part of the builds? I'm guessing it's the `jdk-15+21` one as that's the one I currently see in the build scripts

**Comment by sxa** [comment] 2020-05-19 10:17
Current failure showing in the installer jobs is as follows:
```
C:\Users\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>call powershell.exe ./CreateSourceFolder.AdoptOpenJDK.ps1 
filename : OpenJDK-jdk_x64_windows_hotspot_2020-05-19-03-31.zip don't match regex ^OpenJDK\d+
```
We need to get on top of this and get the builds to green again

**Comment by aahlenst** [comment] 2020-05-19 10:20
This was caused by https://github.com/AdoptOpenJDK/openjdk-installer/pull/208 and https://github.com/AdoptOpenJDK/openjdk-installer/issues/207.

We really need a document that outlines the naming of the artifacts in different stages.

**Comment by M-Davies** [comment] 2020-05-19 11:03
The reason this fails is because JDK-Next does not have a major number in it's tarball.

JDK11 tarballs look like: `OpenJDK11U-jdk_x64_windows_hotspot_2020-05-18-23-34.zip` 
vs the JDK-Next tarballs which are: `OpenJDK-jdk_x64_windows_hotspot_2020-05-19-03-31.zip`. The regex (`^OpenJDK\d+`) is only searching for tarballs that start with `OpenJDK<some-major-number>`. 

This should also cause the [x-linux installer jobs](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_linux) to fail but they seem to ignore the failure:

There is a similar regex in [create_installer_linux.sh](https://github.com/AdoptOpenJDK/openjdk-installer/blob/0940647eb4ce71a9493f585a293bb1a5b97fd951/linux/create_installer_linux.sh#L105) that fails to pick up the file for the same reason 
```
Distribution type not recognized in /home/jenkins/workspace/build-scripts/release/create_installer_linux/OpenJDK-jdk_x64_linux_hotspot_2020-05-19-03-31.tar.gz
Distribution type not recognized in /home/jenkins/workspace/build-scripts/release/create_installer_linux/OpenJDK-jre_x64_linux_hotspot_2020-05-19-03-31.tar.gz
Distribution type not recognized in /home/jenkins/workspace/build-scripts/release/create_installer_linux/OpenJDK-testimage_x64_linux_hotspot_2020-05-19-03-31.tar.gz
Finished: SUCCESS
```
This doesn't fail the job however.

I cannot see the mac jobs yet so I don't know if this is the same for them but I imagine so since the format seems similar to the linux script

So we can either: 
- Modify the installer job to accept just the beginning string of `OpenJDK` and ditch the searching for a major number OR 
- We can modify our scripts to pass in the major version number of the JDK-next job (currently, `15`). This would involve updating [parse](https://github.com/AdoptOpenJDK/openjdk-build/blob/8ac707b6ea357b6c2667d8d9aff99ab200a297d9/pipelines/library/src/common/VersionInfo.groovy#L19) and all of it's dependancies in [VersionInfo.groovy](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/library/src/common/VersionInfo.groovy) to account for JDK tarballs without a major version number.

@aahlenst @sxa Opinions?

**Comment by aahlenst** [comment] 2020-05-19 11:37
If I remember correctly, all installer jobs have to do some archive parsing because the information in the pipelines is incomplete:

:white_check_mark: Complete version string (14.0.1, ...)
:white_check_mark: Major version (8, 9, …)
:white_check_mark: Architecture (x64, …)
:x: Distribution type (JDK, JRE)
:x: VM type (HotSpot, OpenJ9, OpenJ9 XL)
:white_check_mark: Release type (release, nightly, release without publish)

If that information was part of the pipeline, we could eliminate a lot of errors introduced by filename parsing. This filename parsing was a big source of release problems in the past. Ideally, the pipeline should match the information available via the API. This is more than what I listed above.

Why the Linux job isn't failing: There's the filter `**/OpenJDK*_linux_*.tar.gz` that copies the artifacts into the jobs. That's the most specific filter that works all the time, but it is not specific enough because it also copies debug images (and other stuff). So the script has to ignore those artifacts without falling over.

**Comment by sxa** [comment] 2020-05-19 12:37
Either of those options would work @M-Davies - the first is simpler would require updating each time we do a new release (although it's something we could cover in the [new documentation](https://github.com/AdoptOpenJDK/openjdk-build/pull/1746) on creating new releases at Adopt) The rest of the information should still be part of the filename in the JDK head case @aahlenst unless I'm mistaken.

But overall I'm slightly more inclined to lean towards passing parameters down just to increase reliability and reduce dependence on the filename structure.

**Comment by M-Davies** [comment] 2020-05-19 12:41
I'll split off a couple of issues from this for me to work on
- Passing in the JDK-Next version number to VersionInfo.groovy (since this is needed either way)
- Passing down the missing parameters to the installer jobs

**Comment by M-Davies** [comment] 2020-05-19 13:52
From #1750: 
So after doing a little digging, it turns out we ARE actually parsing the JDK next version number downstream to the installers. The [match223](https://github.com/AdoptOpenJDK/openjdk-build/blob/8ac707b6ea357b6c2667d8d9aff99ab200a297d9/pipelines/library/src/common/VersionInfo.groovy#L92) regex successfully picks up the version number and passes it down to the installer. This is not the issue here.

So the problem is in the regex that's in the installer repo (i.e. [this one for windows](https://github.com/AdoptOpenJDK/openjdk-installer/blob/c46b947e6a2567b971554b79dad540a14a26e94f/wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1#L3) and [this one for linux](https://github.com/AdoptOpenJDK/openjdk-installer/blob/c46b947e6a2567b971554b79dad540a14a26e94f/linux/create_installer_linux.sh#L98) (mac isn't needed as it only [needs the individual components](https://github.com/AdoptOpenJDK/openjdk-installer/blob/c46b947e6a2567b971554b79dad540a14a26e94f/pkgbuild/create-installer-mac.sh#L59), not the full file name.

The other issue with missing parameters (distribution and vm types) is still at large however.

**Closed** 2020-05-19 20:19 UTC
Labels: bug

**Comment by karianna** [comment] 2020-05-19 21:58
> From #1750:
> So after doing a little digging, it turns out we ARE actually parsing the JDK next version number downstream to the installers. The [match223](https://github.com/AdoptOpenJDK/openjdk-build/blob/8ac707b6ea357b6c2667d8d9aff99ab200a297d9/pipelines/library/src/common/VersionInfo.groovy#L92) regex successfully picks up the version number and passes it down to the installer. This is not the issue here.
> 
> So the problem is in the regex that's in the installer repo (i.e. [this one for windows](https://github.com/AdoptOpenJDK/openjdk-installer/blob/c46b947e6a2567b971554b79dad540a14a26e94f/wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1#L3) and [this one for linux](https://github.com/AdoptOpenJDK/openjdk-installer/blob/c46b947e6a2567b971554b79dad540a14a26e94f/linux/create_installer_linux.sh#L98) (mac isn't needed as it only [needs the individual components](https://github.com/AdoptOpenJDK/openjdk-installer/blob/c46b947e6a2567b971554b79dad540a14a26e94f/pkgbuild/create-installer-mac.sh#L59), not the full file name.
> 
> The other issue with missing parameters (distribution and vm types) is still at large however.

Does this need a separate issue

**Comment by M-Davies** [comment] 2020-05-20 08:36
@karianna I have made one #1751

**Comment by M-Davies** [comment] 2020-05-20 10:30
Ref the weak `filter` param mentioned in https://github.com/AdoptOpenJDK/openjdk-build/issues/1712#issuecomment-630762333, I have opened a PR to improve the filter to now only accept `OpenJDK-jdk` and `OpenJDK-jre` files https://github.com/AdoptOpenJDK/openjdk-build/pull/1754

**Comment by M-Davies** [comment] 2020-05-22 09:56
Installer is still failing with the same error @Haroon-Khel originally picked up
From https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/4110/console (needs perms to see)
```
First .\SourceDir\OpenJDK15\hotspot\x64\jdk-15.0.0 not exists
Second .\SourceDir\OpenJDK15\hotspot\x64\jdk-15+24 not exists
Third .\SourceDir\OpenJDK15\hotspot\x64\jdk-15.0.0+24 not exists
SOURCE Dir not found / failed
```
Originally documented here => https://github.com/AdoptOpenJDK/openjdk-build/issues/1712#issuecomment-624173979

**Comment by M-Davies** [comment] 2020-05-22 13:20
`SourceDir\OpenJDK\hotspot\x64\jdk-15+24` exists so this is a parsing problem. If https://github.com/AdoptOpenJDK/openjdk-build/pull/1764 gets merged, this should be fixed. Otherwise, we should look into updating the `OpenJDK` part of that path
