### ISSUE TITLE
Wrong link for bundle/Libraries/libserver.dylib

### ISSUE THREAD

**Issue by zakkak** [AdoptOpenJDK/openjdk-build#1210] opened 2019-08-08 08:15 UTC
**Platform:**

AdoptOpenJDK hotspot 8u222-b10
macOS Mojave

**Architecture:**

x86_64

**Description**

Link `/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bundle/Libraries/libserver.dylib` is broken.

```
$ ls -la /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bundle/Libraries/libserver.dylib
lrwxr-xr-x  1 root  wheel  50  8 Aug 11:07 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bundle/Libraries/libserver.dylib@ -> jdk8u222-b10/Contents/Home/lib/server/libjvm.dylib
```

```
$ sudo ln -s -f /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/server/libjvm.dylib /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bundle/Libraries/libserver.dylib
```

Fixes the issue for me.

**Comment by timyates** [comment] 2019-08-08 10:56
Also seems to be broken in 11.0.4 🤔

**Comment by gdams** [comment] 2019-08-08 14:16
@zakkak @timyates did this work on our previous releases  (is this a breaking change or has it always been broken?)

**Comment by gdams** [comment] 2019-08-08 14:18
ahh yes I am aware of this error... We currently do this for the installers but not the tar.gz binaries (https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/pkgbuild/pkgbuild.sh#L64). I need to get the scripts moved across so that it happens at build time rather than installer creation.

**Comment by zakkak** [comment] 2019-08-08 20:21
FWIW this was present in 8u212-b04 as well (not sure about earlier versions) and I am installing using the `*.pkg` file from https://adoptopenjdk.net/archive.html

**Comment by holiday-sunrise** [comment] 2019-08-21 11:41
Had the same Problem.

sudo ln -s -f /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/server/libjvm.dylib /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bundle/Libraries/libserver.dylib

fix it for me

**Comment by NashMiao** [comment] 2020-01-21 05:33
> Had the same Problem.
> 
> sudo ln -s -f /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/server/libjvm.dylib /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bundle/Libraries/libserver.dylib
> 
> fix it for me

It also works for me, thanks!

**Comment by pmarasse** [comment] 2020-04-01 06:31
Same problem here, same fix applied with success

**Comment by aahlenst** [comment] 2020-04-01 07:38
This is a duplicate of https://github.com/AdoptOpenJDK/openjdk-installer/issues/179 and fixed in the latest nightly builds for JDK 8. I haven't checked 11. Maybe someone could.

**Closed** 2020-08-30 07:22 UTC
Labels: bug
