### ISSUE TITLE
create_installer_linux not detecting "distribution" properly

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2344] opened 2021-01-02 17:40 UTC
**What are you trying to do?** Run the nightly pipelines

**Expected behaviour:** installer jobs all produce installers

**Observed behaviour:** "Distribution type not recognised"

**Any other comments:**
Ref: https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_linux/23771/console
```
Copied 4 artifacts from "build-scripts » jobs » jdk » jdk-linux-x64-openj9-linuxXL" build number 39
[create_installer_linux] $ /bin/bash /tmp/jenkins6744301657434369279.sh
Distribution type not recognized in /home/jenkins/workspace/build-scripts/release/create_installer_linux/OpenJDK-debugimage_x64_linux_openj9_linuxXL_2021-01-02-13-22.tar.gz
Distribution type not recognized in /home/jenkins/workspace/build-scripts/release/create_installer_linux/OpenJDK-jdk_x64_linux_openj9_linuxXL_2021-01-02-13-22.tar.gz
Distribution type not recognized in /home/jenkins/workspace/build-scripts/release/create_installer_linux/OpenJDK-jre_x64_linux_openj9_linuxXL_2021-01-02-13-22.tar.gz
Distribution type not recognized in /home/jenkins/workspace/build-scripts/release/create_installer_linux/OpenJDK-testimage_x64_linux_openj9_linuxXL_2021-01-02-13-22.tar.gz
Finished: SUCCESS
```
MAJOR_VERSION is being passed in as 16 despite copying from a JDK17 job - could that be related?

**Comment by aahlenst** [comment] 2021-01-02 21:05
Dupe of https://github.com/AdoptOpenJDK/openjdk-installer/issues/273. No intention to fix.

**Comment by karianna** [comment] 2021-01-03 14:11
> Dupe of [AdoptOpenJDK/openjdk-installer#273](https://github.com/AdoptOpenJDK/openjdk-installer/issues/273). No intention to fix.

Well, there is the long fix as suggested in that issue :-)

**Closed by karianna** 2021-01-03 14:11 UTC
Labels: bug, installer
