### ISSUE TITLE
JDK11 build for Windows is quite different from the java.net build

### ISSUE THREAD

**Issue by ferstl** [AdoptOpenJDK/openjdk-build#642] opened 2018-10-14 21:00 UTC
Maybe this is not an issue but I didn't find another place to ask/report it.

When looking at the OpenJDK 11 builds for Windows from AdoptOpenJDK and jdk.java.net they look quite different.

First, the build from AdoptOpenJDK is about 45% larger then the one from java.net (415MB vs. 287MB):

```
$ du -hs adoptopenjdk-11/
415M    adoptopenjdk-11/

$ du -hs openjdk-11/
287M    openjdk-11/
```

Second, when looking at the `bin/` directory the AdoptOpenJDK build seems to use different DLLs than the java.net build, e.g. VC-Runtime version 12 in AdoptOpenJDK and version 14 in java.net.

Third, the AdoptOpenJDK build contains debugging information in `.pdb` and `.map` files where the one from java.net does not.

I would be interested to understand why the two builds are so different. I would have expected them to be quite similar.

**Comment by karianna** [comment] 2018-10-15 09:12
Hi @ferstl - Great questions!

1.) The alternative DLLs are just a reflection of the toolchain that Adopt uses to build OpenJDK.  This happens to be different to Oracle's OpenJDK build and is likely different to OpenJDK builds by other vendors as well.

2.) We have deliberately left in the debug information as of when we started AdoptOpenJDK our primary audience was developers.

We do need to document these choices and probably remove debug as a default now.

I'll keep this open so we can track that.

**Comment by lwahonen** [comment] 2018-10-27 00:32
Hi,

I just downloaded the AdoptOpenJDK java 8 build, and it doesn't seem to contain any PDB files.

Please make a debug build available for us poor developers who were actually using those :(

Cheers,
Will

**Comment by karianna** [comment] 2018-10-27 06:38
We will, it's just a bit behind in the queue at the minute.  If you'd like to help out then you can join the us at adoptopenjdk.net/slack

**Comment by gdams** [comment] 2019-03-20 20:53
@ferstl can this be closed now?

**Comment by karianna** [comment] 2019-03-20 22:02
This is effectively now a duplicate of #146 - so closing in favour of that one.

**Closed by karianna** 2019-03-20 22:02 UTC
Labels: duplicate, question
