### ISSUE TITLE
Not able to use JDK15 build on centos6

### ISSUE THREAD

**Issue by normanmaurer** [AdoptOpenJDK/openjdk-build#2152] opened 2020-10-16 07:23 UTC
Hi there,

I am not sure if this is the right place to report this but I tried to use the latest AdoptJDK 15 release on centos6 and it failed with:

/jdk/bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /jdk/bin/../lib/libjli.so)

Is this expected ?

**Comment by aahlenst** [comment] 2020-10-16 07:27
Duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/2097.

**Closed by aahlenst** 2020-10-16 07:27 UTC
