### ISSUE TITLE
file permissions Issue - windows

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1878] opened 2020-06-11 08:55 UTC
**jdk11u-windows-x64-openj9**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/630/console

`Execution error: Unable to get file permissions`

**Comment by sxa** [comment] 2020-06-12 14:56
Potential duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1360 so marking as duplicate but leaving open until verified (https://github.com/AdoptOpenJDK/openjdk-build/pull/1871 is a potential fix)

**Comment by M-Davies** [comment] 2020-06-16 08:48
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/596/console
```
19:43:49  Starting building: build-scripts » release » create_installer_windows #4760
[Pipeline] copyArtifacts
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
19:48:08  Execution error: Unable to get file permissions
```

**Comment by M-Davies** [comment] 2020-06-17 08:41
https://github.com/AdoptOpenJDK/openjdk-build/pull/1896/files might print out the stacktrace for us

**Comment by M-Davies** [comment] 2020-06-18 08:06
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/648/console
```
19:02:41  Scheduling project: build-scripts » release » create_installer_windows
19:02:47  Starting building: build-scripts » release » create_installer_windows #4841
[Pipeline] copyArtifacts
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
19:07:20  Execution error: hudson.os.PosixException: Unable to get file permissions null
```

**Comment by archanaNogriya** [comment] 2020-06-18 08:08
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9-windowsXL/330/console

```
22:01:43  Scheduling project: build-scripts » release » create_installer_windows
22:12:53  Starting building: build-scripts » release » create_installer_windows #4847
[Pipeline] copyArtifacts
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
22:15:11  Execution error: hudson.os.PosixException: Unable to get file permissions null
```

**Comment by karianna** [comment] 2020-06-18 15:26
Can we print out the file permissions at that stage owner/group etc.

**Comment by M-Davies** [comment] 2020-06-19 09:04
#1913 [has been reverted](https://github.com/AdoptOpenJDK/openjdk-build/pull/1915) since it caused build breaks (https://github.com/AdoptOpenJDK/openjdk-build/issues/1914). I have another idea to try and use `context.sh` [without the script tag](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L211). It may be that the script tag executes the command on the master server https://code-maven.com/jenkins-pipeline-running-external-programs

**Comment by sxa** [comment] 2020-06-19 09:40
@M-Davies Can you trigger a re-run of the builds affected by this please now that the fix is in?

**Comment by M-Davies** [comment] 2020-06-19 09:58
> @M-Davies Can you trigger a re-run of the builds affected by this please now that the fix is in?

@sxa Done

**Comment by andrew-m-leonard** [comment] 2020-06-29 08:27
@M-Davies still failing: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/662/

**Comment by adamfarley** [comment] 2020-06-29 15:21
Could this be related to #1834?

[These](https://issues.jenkins-ci.org/browse/JENKINS-51488) [two](https://www.gitmemory.com/issue/ingenieux/awseb-deployment-plugin/92/569938510) websites show cases where a NoSuchFileException caused an exception that showed the same error that we're seeing here.

**Comment by andrew-m-leonard** [comment] 2020-06-29 15:27
I would suggest adding "debug" echos() to the groovy in the area we think this is occuring, and re-running repeatedly on a suitable Windows box...

**Comment by douph1** [comment] 2020-06-30 10:46
https://github.com/AdoptOpenJDK/openjdk-build/pull/1942 is a start of "debug echo" as it must print the full stacktrace and not just the message

**Comment by M-Davies** [comment] 2020-07-08 09:18
I suspect @andrew-m-leonard fixed this when [he increased the job retention](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1593593846235300) as I haven't seen this for a while now. The error message we were getting would make sense as it wouldn't be possible to the file permissions if there was no file to get the permissions from!

**Closed by M-Davies** 2020-07-08 09:18 UTC
Labels: buildbreak
