### ISSUE TITLE
makejdk-any-platform.sh is not suitable way to run build trough docker

### ISSUE THREAD

**Issue by grzesuav** [AdoptOpenJDK/openjdk-build#689] opened 2018-10-25 17:22 UTC
Currently to run dockerized build we need to execute
`./makejdk-any-platform.sh --docker --clean-docker-build jdk10u  `
where we passing option in cmdline to execute build in docker.

Configuration part of this script (`config_init.sh`) is executed on local machine, and setting configured here are passed inside docker container, which is incorrect.

Alternative would be to create wrapper to run everything in container as normal build goes (so copy `makejdk-any-platform.sh` and the rest of files inside the container and execute here)

I encounter problem when I tried to execute `./makejdk-any-platform.sh --docker --clean-docker-build jdk10u ` and it pass my local java path as boot sdk path, when inside container zulu-9 is used

**Comment by grzesuav** [comment] 2019-02-21 16:37
@karianna @dinogun who would be best person to ask for assistance and review?
What must be done in PR :
* artifact is not located outside docker container 
What  should be done :
* drop any docker related setting from main setting array - they should be used only by wrapper script

**Comment by grzesuav** [comment] 2019-02-21 16:37
Related to https://github.com/AdoptOpenJDK/openjdk-build/issues/689

**Comment by Willsparker** [comment] 2019-10-28 11:09
Another issue caused by this: #1293

**Comment by sxa555** [comment] 2019-12-04 13:52
Merged. Closing. Please re-open (or raise another issue) if anyone finds a problem with it

**Closed by sxa555** 2019-12-04 13:52 UTC
Labels: bug
