### ISSUE TITLE
JRE foldername should be "jre-11+28" and not "jdk-11+28-jre"

### ISSUE THREAD

**Issue by alexhass** [AdoptOpenJDK/openjdk-build#617] opened 2018-10-07 19:46 UTC
Just extracted the folder and have seen the folder is named very strange. We should follow Oracle. They name the folder `jre-[version]`, too. Prefixing with JDK is missleading if this is the JRE only.

**Comment by alexhass** [comment] 2018-10-07 22:06
Aside, schould it not mean "OpenJRE" where "OpenJDK" is normally used?

**Comment by karianna** [comment] 2018-10-08 08:50
Curiously no, it's officially the JRE component of OpenJDK

**Comment by karianna** [comment] 2018-10-08 12:59
agree on the zip file name :-)

**Comment by sxa555** [comment] 2018-10-17 11:14
> Maybe, but in the zip we should prefix the folder with jre- like oracle

That's a good shout actually ... As an aside at one point I think I did toy with having the filename say "OpenJRE" when I did the initial work to produce the JRE packages but decided it didn't look right ;-)

**Comment by alexhass** [comment] 2018-10-17 17:11
Yeah, but here we should fix it. The install folder is already clear... „C:\Program Files\AdoptOpenJDK\jre-11.0.0.18“ does not require more „jdk“... and it is really the jre. Let‘s follow Oracle naming here, please.

**Comment by karianna** [comment] 2018-10-17 18:29
@johnoliver perhaps one to fix before the 192 release

**Comment by gdams** [comment] 2019-03-11 11:05
looks like a simple change to this line: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L424

**Comment by breun** [comment] 2019-03-21 16:52
There are no JRE builds for Oracle OpenJDK anymore by the way, only full JDK's. :)

**Comment by asbachb** [comment] 2020-02-17 00:45
relates to https://bugs.openjdk.java.net/browse/JDK-8200132

**Comment by M-Davies** [comment] 2020-05-18 12:41
> looks like a simple change to this line: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L424

@gdams Is this still true? I notice that the link is now pointing to a gradle instance which doesn't seem like it's related to this issue?

**Comment by karianna** [comment] 2020-05-21 22:57
> > looks like a simple change to this line: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L424
> 
> @gdams Is this still true? I notice that the link is now pointing to a gradle instance which doesn't seem like it's related to this issue?

Build scripts have changed significantly since this bug report was posted.  @johnoliver - would changing the name cause any API incompatibility issues etc?

**Comment by aahlenst** [comment] 2020-08-29 10:42
Duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/1016.

**Closed by aahlenst** 2020-08-29 10:42 UTC
Labels: bug
