### ISSUE TITLE
openjdk8 and openjdk9 hotspot macos builds failed and no SDK published

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#435] opened 2018-08-09 14:49 UTC
Both openjdk8 and openjdk9 hotspot macos builds failed for same issue for more than a month.
https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_macos/
https://ci.adoptopenjdk.net/job/openjdk9_build_x86-64_macos/

Looking at the output SDK is build successfully. Jenkins build failed for some lib missing, which casued no tests builds were triggered and no SDK was published.
**[Error] j2re-image/lib/libfreetype.dylib.6 does not exist in the j2re-image folder, please check if this is the right folder to refer to, aborting copy process**

```
openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_08_08_17_01-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)


Removing unnecessary files now...
Fetching the first tag from the OpenJDK git repo...
Currently at '/Users/jenkins/workspace/openjdk8_build_x86-64_macos/openjdk/build/macosx-x86_64-normal-server-release/images'
moving j2sdk-image to jdk8u181-b13
moving j2re-image to jre8u181-b13
Finished removing unnecessary files from jdk8u181-b13 and jre8u181-b13
PERFORM_COPYING=false
 Skipping copying of the free font library to jdk8u181-b13, does not apply for this version of the JDK. 
PERFORM_COPYING=true
 Performing copying of the free font library to j2re-image, applicable for this version of the JDK. 
[Error] j2re-image/lib/libfreetype.dylib.6 does not exist in the j2re-image folder, please check if this is the right folder to refer to, aborting copy process...
Archiving artifacts
‘OpenJDK*.tar.gz’ doesn’t match anything
```

**Comment by karianna** [comment] 2018-08-09 15:06
Duplicate of #354 - new build scripts resolve this - should have releases soon.

**Closed by karianna** 2018-08-09 15:06 UTC
