### ISSUE TITLE
jconsole from jdk8u222-b10 will not launch on solaris

### ISSUE THREAD

**Issue by antman-health** [AdoptOpenJDK/openjdk-build#1180] opened 2019-07-19 04:48 UTC
**Platform:**
Sun Solaris 11

**Architecture:**
Sparc sun4v

Please describe the issue that you are having with our binaries and if possible how to recreate it.

The jconsole program will not launch from AdoptOpenJDK jdk8u222-b05. 
Using X-11 forwarding in putty and X-ming xserver on Windows 10. 
Same issue with jdk8u212-b04. 
jconsole will launch ok from Oracle jdk1.7.0_80 on same server.

To reproduce:
```bash
cd jdk8u222-b10/bin
./jconsole
```

[Does not launch X window]
Need to Ctrl-c to interrupt.

**Comment by gdams** [comment] 2019-07-19 11:00
@antman-health did this work with the previous release? or has this never worked?

**Comment by karianna** [comment] 2019-07-19 11:21
And should that be `jdk8u222-b10`?

**Comment by antman-health** [comment] 2019-07-21 22:27
Sorry for late reply, back at work now.

No didn’t work with the previous release which was jdk8u212-b04.

Thanks
AY

**Comment by antman-health** [comment] 2019-07-21 22:28
Yes, should be jdk8u222-b10. Jconsole not launching X window with that version as well.

Thanks
AY

**Comment by gdams** [comment] 2019-07-22 09:27
Okay so I have confirmed the following steps work on Solaris 10:

```bash
cd jdk8u222-b10/bin
./jconsole
```

But I also get the same issue when I try to run the above steps on Solaris 11. I do get the same issue with the Bellsoft Liberica binary here (https://download.bell-sw.com/java/8u222/bellsoft-jdk8u222-solaris-sparcv9.tar.gz). @antman-health could you also confirm for me that the Bellsoft binary doesn't work for you? 

I'm going to do some more digging here.

**Comment by gdams** [comment] 2019-07-22 09:40
This is also a bug in the latest Zulu OpenJDK build: https://cdn.azul.com/zulu/bin/zulu8.40.0.25-ca-jdk8.0.222-solaris_sparcv9.zip

I did however manage to get an Oracle Java 8 binary to work so this looks like an OpenJDK bug.

**Comment by gdams** [comment] 2019-07-22 11:06
@antman-health I've found the fix. This is almost certainly to do with the fact that you don' have any fonts on your system. The big difference between openjdk and oracle's builds is that they ship the base fonts with their jdk, whereas openjdk is left entirely at the mercy of the OS to provide fonts. 

give this a try:

```bash
pkg install  font/truetype/dejavu
```

I will close this issue as this worked for me. Please re-open if you still hit issues

**Closed by gdams** 2019-07-22 11:06 UTC
Labels: bug

**Comment by antman-health** [comment] 2019-07-22 21:56
That’s excellent, great work, thanks for the quick response.

Thanks
AY
