### ISSUE TITLE
jdk11u-linux-aarch64-openj9-linuxXL : java.lang.module.FindException while creating jdk images 

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1831] opened 2020-06-08 08:53 UTC
**Platform:**
jdk11u-linux-aarch64-openj9-linuxXL

Build Machine : build-packet-centos74-armv8-1 in

**Architecture:**
{
00:31:54      "ARCHITECTURE": "aarch64",
00:31:54      "TARGET_OS": "linux",
00:31:54      "VARIANT": "openj9",
00:31:54      "JAVA_TO_BUILD": "jdk11u",
00:31:54      "TEST_LIST": [
00:31:54          "sanity.openjdk",
00:31:54          "sanity.system",
00:31:54          "extended.system"
00:31:54      ],
00:31:54      "SCM_REF": "",
00:31:54      "BUILD_ARGS": "",
00:31:54      "NODE_LABEL": "centos7&&build&&linux&&aarch64",
00:31:54      "CONFIGURE_ARGS": "--with-noncompressedrefs --disable-ccache --enable-dtrace=auto",
00:31:54      "OVERRIDE_FILE_NAME_VERSION": "",
00:31:54      "ADDITIONAL_FILE_NAME_TAG": "linuxXL",
00:31:54      "RELEASE": false,
00:31:54      "PUBLISH_NAME": "",
00:31:54      "ADOPT_BUILD_NUMBER": "",
00:31:54      "ENABLE_TESTS": true,
00:31:54      "CLEAN_WORKSPACE": false
00:31:54  }

Please describe the issue that you are having with our binaries and if possible how to recreate it.

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/234/console

`01:45:45  Error: Hash of java.rmi (f6b59c404493651c21f2b772bd6d7130454803fa2b37019c7d1d4c385df95bc5) differs to expected hash (f14bb9705406aaada983c3e3b7778b3433fe94a44b92677e1369d262fc114d03) recorded in java.base
01:45:45  java.lang.module.FindException: Hash of java.rmi (f6b59c404493651c21f2b772bd6d7130454803fa2b37019c7d1d4c385df95bc5) differs to expected hash (f14bb9705406aaada983c3e3b7778b3433fe94a44b92677e1369d262fc114d03) recorded in java.base
01:45:45  	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
01:45:45  	at java.base/java.lang.module.Resolver.checkHashes(Resolver.java:461)
01:45:45  	at java.base/java.lang.module.Resolver.finish(Resolver.java:360)
01:45:45  	at java.base/java.lang.module.Configuration.<init>(Configuration.java:141)
01:45:45  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:424)
01:45:45  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:220)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:486)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:396)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:272)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:54)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)
01:45:45  Images.gmk:93: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-normal-server-release/images/jdk/bin/java' failed
01:45:45  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-normal-server-release/images/jdk/bin/java] Error 1
01:45:45  make/Main.gmk:394: recipe for target 'jdk-image' failed
01:45:45  gmake[2]: *** [jdk-image] Error 1
01:45:45  gmake[2]: *** Waiting for unfinished jobs....
01:45:45  Error: Hash of jdk.net (cd433f60417f0cefe8a4be298ea1694a1d57540f9bbfbe40b39d5e6d6a56c441) differs to expected hash (33f57a14ce1e90e52abd07dfe6efb63571dc358d32e5a46246173b64d3d2ac0d) recorded in java.base
01:45:45  java.lang.module.FindException: Hash of jdk.net (cd433f60417f0cefe8a4be298ea1694a1d57540f9bbfbe40b39d5e6d6a56c441) differs to expected hash (33f57a14ce1e90e52abd07dfe6efb63571dc358d32e5a46246173b64d3d2ac0d) recorded in java.base
01:45:45  	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
01:45:45  	at java.base/java.lang.module.Resolver.checkHashes(Resolver.java:461)
01:45:45  	at java.base/java.lang.module.Resolver.finish(Resolver.java:360)
01:45:45  	at java.base/java.lang.module.Configuration.<init>(Configuration.java:141)
01:45:45  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:424)
01:45:45  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:220)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:486)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:396)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:272)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:54)
01:45:45  	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)
01:45:45  Images.gmk:104: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-normal-server-release/images/jre/bin/java' failed
01:45:45  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-normal-server-release/images/jre/bin/java] Error 1
01:45:45  make/Main.gmk:397: recipe for target 'legacy-jre-image' failed
01:45:45  gmake[2]: *** [legacy-jre-image] Error 1
01:45:47  `

**Comment by DanHeidinga** [comment] 2020-06-09 14:24
fyi @knn-k @0xdaryl 

Can you take a look at this aarch64 build issue on the XL package?

**Comment by knn-k** [comment] 2020-06-10 00:31
This looks like a duplicate of #1804.

**Comment by knn-k** [comment] 2020-06-10 01:55
I tried building the XL runtime 3 times on a 32-core AArch64 Linux machine, but I could not recreate the error.

**Comment by karianna** [comment] 2020-06-10 08:11
Closing this in favour of #1804.  LMK if you want anything copied across.

**Closed by karianna** 2020-06-10 08:11 UTC
Labels: bug, duplicate, openj9
