### ISSUE TITLE
Openjdk 11+ build need also build test-image

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#248] opened 2018-03-06 22:30 UTC
Some tests of test/jdk and test/hotspot need jdk test native library, which has to be generated at build time of the test jdk by invoking "make test-image"

It appears as though the native test libraries are currently not being built as part of the Java10 builds at AdoptOpenJDK, as we do not find libraries under images/test/jdk/jtreg/native for those builds.

https://download.java.net/openjdk/testresults/10/docs/howtoruntests.html

-nativepath:{location of the jdk test native library}: This has to be generated at build time of the test jdk by invoking "make test-image". These libraries are located in the build directory under "images/test/jdk/jtreg/native/"

**Comment by karianna** [comment] 2018-03-16 18:10
#263 should resolve this.

**Comment by sophia-guo** [comment] 2018-04-26 20:40
#263 build test-image, which is under same folder level of jdk or ${OPENJDK_REPO_TAG} - named test. However when doing archive only ${OPENJDK_REPO_TAG} is tar-ed. createOpenJDKTarArchive() need to update so when untared jdk folder `createOpenJDKTarArchive()` and `test` are expected.

**Comment by sophia-guo** [comment] 2018-04-27 13:51
Given it a second thought we probably need to tar the JDK and TestImage separately as TestImage should not be part of released sdk? The story would be like:  SDK build create SDK and testImage , test build consume SDK and testImage, and then if test build is good SDK itself will be published (testImage is ignored as it should not be part of releases) ?

**Comment by sophia-guo** [comment] 2018-06-14 17:22
@renfeiw tesing

**Comment by karianna** [comment] 2019-01-10 15:20
@sophia-guo Is this needed for Java 11?  If not then we'll close as we're no longer supporting Java 10.

**Comment by sophia-guo** [comment] 2019-01-10 18:42
yes, this is also required for Java11. It is required for 10+.

**Comment by navyxliu** [comment] 2019-02-13 02:32
I am working on Corretto11 regression test. I am very interested in this issue and its resolution.

So far, I have identified 10 test failures due to 'Error. Use -nativepath to specify the location of native code'

java/nio/channels/FileChannel/directio/DirectIOTest.java
java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java
compiler/aot/calls/fromAot/AotInvokeDynamic2NativeTest.java
compiler/aot/calls/fromAot/AotInvokeInterface2NativeTest.java
compiler/aot/calls/fromAot/AotInvokeSpecial2NativeTest.java
compiler/aot/calls/fromAot/AotInvokeStatic2NativeTest.java
compiler/aot/calls/fromAot/AotInvokeVirtual2NativeTest.java
compiler/aot/calls/fromNative/NativeInvokeSpecial2AotTest.java
compiler/aot/calls/fromNative/NativeInvokeStatic2AotTest.java
compiler/aot/calls/fromNative/NativeInvokeVirtual2AotTest.java

**Comment by jerboaa** [comment] 2019-02-13 08:40
IMO this isn't entirely a openjdk-build issue only. What if somebody has a build with test libs already? I'd imagine the test framework should allow for a path to be set via some environment variable which is then passed to via `-nativepath` to jtreg.

**Comment by smlambert** [comment] 2019-02-13 15:01
Agreed @jerboaa - as discussed in Slack, you can leverage JTREG_EXTRA_OPTIONS for the use case of having your own build, and a path to the native test libs.

This issue is more for us to be able to automate native testing in the AdoptOpenJDK pipelines.

**Comment by smlambert** [comment] 2019-08-07 02:42
I would like to request this gets addressed within the next 1 or 2 milestones, it is blocking us from enabling native openjdk tests in the pipelines.

**Comment by karianna** [comment] 2019-08-07 14:39
> I would like to request this gets addressed within the next 1 or 2 milestones, it is blocking us from enabling native openjdk tests in the pipelines.

I've pinned the issue

**Comment by karianna** [comment] 2019-08-24 06:39
@jerboaa Could I ask you to take a look at this one - I think you got it working for upstream builds correct?

**Comment by jerboaa** [comment] 2019-08-26 07:57
@karianna OK. I'll try to take a look this week.

**Comment by jerboaa** [comment] 2019-09-03 12:05
@smlambert @sophia-guo: This job has the testimage artifact as well for early testing. Let me know if that'll work for you:
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/133/

**Comment by sophia-guo** [comment] 2019-09-03 14:59
Thanks @jerboaa. I will try today or tomorrow and let you know.

**Comment by sophia-guo** [comment] 2019-09-03 16:11
@jerboaa the prtestbuid https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/133/ doesn't have any  **/*.tar.gz,**/*.tgz,**/*.zip,**/*.jar artifacts. Is there any other way that I can download the test image you have built and archived? Ideally it should be available same as other build artifacts, e.t.c. jre|jdk iamge artifacts.

**Comment by jerboaa** [comment] 2019-09-03 17:44
@sophia-guo Try this one: https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/134/

**Comment by sophia-guo** [comment] 2019-09-04 17:42
@jerboaa it's great! thanks.

**Comment by jerboaa** [comment] 2019-09-04 18:00
@sophia-guo Glad to hear that. Just need to get the PR merged then ;-)

**Closed** 2019-09-06 15:04 UTC
Labels: enhancement
