### ISSUE TITLE
aarch64 build failure, Hash of java.rmi (...) differs to expected hash 

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1804] opened 2020-06-01 07:44 UTC
**Platform:**
aarch64
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/223/consoleFull
```
01:05:10  * For target support_images_jre:
01:05:10  Error: Hash of java.rmi (5fe5f05db30334fea7371af06d42a7f7e5417acae4022df3ddec5c8d8aaf5e02) differs to expected hash (24f0620202e6705b53c79e3827358915385f2c46b4c91b1b65443e954b4df58f) recorded in java.base
01:05:10  java.lang.module.FindException: Hash of java.rmi (5fe5f05db30334fea7371af06d42a7f7e5417acae4022df3ddec5c8d8aaf5e02) differs to expected hash (24f0620202e6705b53c79e3827358915385f2c46b4c91b1b65443e954b4df58f) recorded in java.base
01:05:10  	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
01:05:10  	at java.base/java.lang.module.Resolver.checkHashes(Resolver.java:461)
01:05:10  	at java.base/java.lang.module.Resolver.finish(Resolver.java:360)
01:05:10  	at java.base/java.lang.module.Configuration.<init>(Configuration.java:141)
01:05:10  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:424)
01:05:10  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
01:05:10  	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:220)
01:05:10  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:486)
01:05:10  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:396)
01:05:10  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:272)
01:05:10  	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:54)
01:05:10  	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)
```

I am suspecting this maybe an openjdk build concurrency issue.
Workaround maybe reducing the aarch64 concurrency, it is currently using 29 jobs:
```
00:43:14  * Cores to use:   29
```

**Comment by M-Davies** [comment] 2020-06-01 08:22
Previously seen as an intermittent https://github.com/AdoptOpenJDK/openjdk-build/issues/1450#issuecomment-607195768

**Comment by sxa** [comment] 2020-06-01 13:05
That machine has far more than 29 cores so that number shouldn't be a problem (unless there is a problem in the makefile that this happens to exacerbate). Do we know if this is only showing up on one machine?

**Comment by andrew-m-leonard** [comment] 2020-06-01 13:49
I suspect this might be showing up a jdk11 makefile issue, really hard to tell and work out, it's just 29 jobs is a large number.
What I am saying with a bit of luck the problem may dissappear with say 10jobs, as I am suspecting java.base got its hashes generated on a non-complete java.rmi

**Comment by andrew-m-leonard** [comment] 2020-06-29 08:13
and again: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/269/consoleFull

**Comment by knn-k** [comment] 2020-06-29 22:24
I wrote a small program that calculates the hash value of a jmod file for reproducing the problem.
But I haven't been able to reproduce the wrong hash value.

**Comment by knn-k** [comment] 2020-06-30 01:10
Similar error with Hotspot on amd64: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944738

**Comment by Akira1Saitoh** [comment] 2020-06-30 09:06
I could reproduce the problem on cent7-aarch64-1. I was also able to reproduce by manually launching `jmod` command used by build process, but the probability is very low (1/200 times so far).

**Comment by andrew-m-leonard** [comment] 2020-06-30 16:43
I started to have a think about this one, as it's causing regular build breaks... and I was wondering what reasons could the be for the "recorded" java.base hash, being different to the dependent jmod hash? I can think of the following:
1. Crypto "hash" logic has some odd timing bug
2. Concurrency in the GNU make workers causes the java.base recorded hash to be on an incomplete java.rmi jmod? (Discounted this, by running a test build --with-jobs=1)
3. GNU makefile has a basic dependency error such that recorded hash is done at wrong time, prior to java.rmi being completed?
4. ???

**Comment by andrew-m-leonard** [comment] 2020-07-01 15:23
Running a build with some manual debug added: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/andrew-jdk11u-linux-aarch64-openj9-linuxXL/

**Comment by Akira1Saitoh** [comment] 2020-07-02 00:45
> 2. Concurrency in the GNU make workers causes the java.base recorded hash to be on an incomplete java.rmi jmod? (Discounted this, by running a test build --with-jobs=1)
> 3. GNU makefile has a basic dependency error such that recorded hash is done at wrong time, prior to java.rmi being completed?

I think this is not a problem with GNU make or makefile because I can reproduce the hash mismatch error with simply running `jmod` command.

**Comment by knn-k** [comment] 2020-07-02 00:54
What is the version of OpenSSL on the build server?

**Comment by Akira1Saitoh** [comment] 2020-07-02 00:56
Surprisingly, I saw that sometimes the output of `sha256sum` command was incorrect on cent7-aarch64-1.

> ...
> fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f build/linux-aarch64-normal-server-release/images/jmods/java.rmi.jmod
> hash of java.rmi is fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f
> run 47: ok
> fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f build/linux-aarch64-normal-server-release/images/jmods/java.rmi.jmod
> hash of java.rmi is fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f
> run 48: ok
> fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f build/linux-aarch64-normal-server-release/images/jmods/java.rmi.jmod
> hash of java.rmi is fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f
> run 49: ok
> fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f build/linux-aarch64-normal-server-release/images/jmods/java.rmi.jmod
> hash of java.rmi is fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f
> run 50: ok
> 264ac9684a28d03af37aaedf683a52d02405b239c8911b74ec780c9a02bd0288 build/linux-aarch64-normal-server-release/images/jmods/java.rmi.jmod
> hash of java.rmi is 264ac9684a28d03af37aaedf683a52d02405b239c8911b74ec780c9a02bd0288
> hash does not match
> [jenkins@cent7-arm8-1 openj9-openjdk-jdk11]$ sha256sum build/linux-aarch64-normal-server-release/images/jmods/java.rmi.jmod 
> fa13eb1483a0fbc03164e113d4d7d23525888d8607b2fc4472c2ff4dd9bce55f  build/linux-aarch64-normal-server-release/images/jmods/java.rmi.jmod

`sha256sum` command uses libcrypto.so which is part of OpenSSL.

> [jenkins@cent7-arm8-1 build]$ ldd /usr/bin/sha256sum
>         linux-vdso.so.1 =>  (0x0000ffffb08a0000)
>         libcrypto.so.10 => /lib64/libcrypto.so.10 (0x0000ffffb0670000)
>         libc.so.6 => /lib64/libc.so.6 (0x0000ffffb04e0000)
>         /lib/ld-linux-aarch64.so.1 (0x0000ffffb08b0000)
>         libdl.so.2 => /lib64/libdl.so.2 (0x0000ffffb04b0000)
>         libz.so.1 => /lib64/libz.so.1 (0x0000ffffb0470000)
> [jenkins@cent7-arm8-1 build]$ ls -l /lib64/libcrypto.so.10
> lrwxrwxrwx 1 root root 19 Sep 18  2019 /lib64/libcrypto.so.10 -> libcrypto.so.1.0.2k

**Comment by andrew-m-leonard** [comment] 2020-07-02 08:07
That is interesting i've just created a job doing a sha256sum loop, and in one instance out of 10000 it got a different hash:
HASH=cfdab6087d46a53a4de3a7f2e42791d7e44cfa1e553206127c487541c0e207f3
ERROR hash=7b9d06d1412b71840e2576b2dcccfce7f57c5e5427a576507551ac7b5a9e3db1

however, having run the job numerous times since it hasn't failed again... weird!

**Comment by andrew-m-leonard** [comment] 2020-07-02 09:30
build-packet-centos74-armv8-1, openssl version : 
OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by sxa** [comment] 2020-07-02 09:31
> @andrew-m-leonard What is the version of OpenSSL on the build server?

1.0.2k as supplied by RedHat

**Comment by andrew-m-leonard** [comment] 2020-07-02 09:33
@sxa can we upgrade openssl, as it's looking like a bug in openssl ?

**Comment by andrew-m-leonard** [comment] 2020-07-02 09:34
or a file system issue, returning different file data...?

**Comment by sxa** [comment] 2020-07-02 09:35
Well we could build our own one but we SHOULD be building with the one supplied with the OS so arguably RedHat should fix it. I'm tempted to suggest it might be file system related. I guess https://ci.adoptopenjdk.net/job/andrew-aarch-hash-debug/10/console is the run where you had one failure out of ... a lot?

**Comment by andrew-m-leonard** [comment] 2020-07-02 09:35
> Well we could build our own one but we SHOULD be building with the one supplied with the OS so arguably RedHat should fix it. I'm tempted to suggest it might be file system related. I guess https://ci.adoptopenjdk.net/job/andrew-aarch-hash-debug/10/console is the run where you had one failure out of ... a lot?

Correct job 10

**Comment by knn-k** [comment] 2020-07-02 10:02
>or a file system issue, returning different file data...?

Yes, that is another possibility.
I suspect OpenSSL because there are some other known intermittent issues for AArch64 OpenJ9 that may be related to OpsnSSL.

**Comment by Akira1Saitoh** [comment] 2020-07-02 10:47
If this is a file system issue, the error can happen with other checksum command which does not use OpenSSL, such as `cksum` command. I think doing a `cksum` loop instead of `sha256sum` might help narrow down the problem.

**Comment by andrew-m-leonard** [comment] 2020-07-02 14:22
I can't reliably repeat the failure, i've had a couple more since, but the failures happen at an arbitrary moment, then it works for ages.....
Trying to get a job that runs repeatedly and recreates it occaisionally.

**Comment by andrew-m-leonard** [comment] 2020-07-02 14:24
seems when it has failed running the job, it fails straight away... when it doesn't fail the job iterates and succeeds. It's as if the "disk" sometimes wakes up in a bad mood!!

**Comment by andrew-m-leonard** [comment] 2020-07-03 09:09
@sxa it's difficult to replicate, but we know it happens during the build about 1 in 3.... Can we easily move the jenkins workspace to the ram drive? or do we have another machine we can setup?
the test-aws-rhel- machines are not setup for building...?

**Comment by sxa** [comment] 2020-07-03 11:11
The workspaces are very large and obviously using a ramdisk means you're taking memory away from the machine for doing realy work, so while it would be possible to do it temporarily for testing I wouldn't advocate doing that permanently.

> the test-aws-rhel- machines are not setup for building...?

Was that a question or a statement - we generally set them up the same way from generic playbooks so I would expect that they would have all the build prereqs on them.

**Comment by sxa** [comment] 2020-07-03 12:04
I've just tried running 128 copies of sha256sum in parallel validating the checksum of `java.rmi.jmod` one million times each on the machine. Zero fialures (note that his won't have forked 1M copies of the sha256sum binary - it starts up once for each parallel job and does the check 1M times)

**Comment by andrew-m-leonard** [comment] 2020-07-06 06:42
@sxa it's very perculiar when it happens, a straitght forward loop seems to work...
I've created a more bizarre job that runs every 10 mins, and it failed last night on 2 subsequent jobs but worked fine for all the rest of the weekend, how lucky is that?!
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/andrew-aarch-hash-debug/483/
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/andrew-aarch-hash-debug/484/

**Comment by andrew-m-leonard** [comment] 2020-07-06 10:44
@sxa test-aws-rhel76-armv8-2 does not have jdk-boot-dir set correctly, causing error below:
```
11:36:11  /home/jenkins/workspace/andrew-jdk11u-linux-aarch64-openj9-linuxXL/build-farm/../makejdk-any-platform.sh --clean-git-repo --jdk-boot-dir  --configure-args --with-noncompressedrefs --disable-ccache --enable-dtrace=auto --disable-warnings-as-errors --with-openssl=system --target-file-name OpenJDK11U-jdk_aarch64_linux_openj9_linuxXL_2020-07-06-10-36.tar.gz -r https://github.com/ibmruntimes/openj9-openjdk-jdk11 -b openj9 --use-jep319-certs --build-variant openj9 jdk11u
11:36:11  Starting /home/jenkins/workspace/andrew-jdk11u-linux-aarch64-openj9-linuxXL/build-farm/../makejdk-any-platform.sh to configure, build (Adopt)OpenJDK binary
11:36:11  Parsing opt: --clean-git-repo
11:36:11  Possible opt arg: --jdk-boot-dir
11:36:11  Parsing opt: --jdk-boot-dir
11:36:11  Possible opt arg: --configure-args
11:36:11  Parsing opt: --with-noncompressedrefs --disable-ccache --enable-dtrace=auto --disable-warnings-as-errors --with-openssl=system
11:36:11  Possible opt arg: --target-file-name
11:36:11  Invalid build.sh option: --with-noncompressedrefs --disable-ccache --enable-dtrace=auto --disable-warnings-as-errors --with-openssl=system
```

**Comment by andrew-m-leonard** [comment] 2020-07-06 10:51
@sxa fixed, i've added JDK10_BOOT_DIR to test-aws-rhel76-armv8-2 node configuration

**Comment by andrew-m-leonard** [comment] 2020-07-06 18:45
@sxa gcc compiler is not configured correctly on test-aws-rhel76-armv8-2, it's picking up gcc 4.8.5

**Comment by sxa** [comment] 2020-07-06 20:28
> @sxa gcc compiler is not configured correctly on test-aws-rhel76-armv8-2, it's picking up gcc 4.8.5

I've updated that machine only - it had gcc 7.3 on it but we removed the support for picking that up automatically. It should now find 7.5

**Comment by sxa** [comment] 2020-07-06 20:34
Kicked off https://ci.adoptopenjdk.net/view/work%20in%20progress/job/andrew-jdk11u-linux-aarch64-openj9-linuxXL/43/

**Comment by andrew-m-leonard** [comment] 2020-07-07 07:25
thanks @sxa 
So my hash debug failed again last night, 4 jobs in a row!! on build-packet-centos74-armv8-1
01:47am->02:10am
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/andrew-aarch-hash-debug/613/console
This is too coincidental to me, which I am thinking lends itself to a problem on build-packet-centos74-armv8-1.
I now have an hourly build job running on test-aws-rhel76-armv8-2, to see if the problem exists on their: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/andrew-jdk11u-linux-aarch64-openj9-linuxXL/

**Comment by adamfarley** [comment] 2020-07-07 08:47
Another failure on build-packet-centos74-armv8-1.
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/284/consoleFull

**Comment by andrew-m-leonard** [comment] 2020-07-07 08:49
@sxa i'll leave my build job running hourly through today on test-aws-rhel76-armv8-2
and if all look good i'll switch the build "tag" over to this machine...?

**Comment by andrew-m-leonard** [comment] 2020-07-07 10:43
Created infra issue to replace machine: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1431

**Comment by lumpfish** [comment] 2020-07-15 15:39
July 2020 release build failed - also on build-packet-centos74-armv8-1 : https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/293/consoleFull

**Comment by sxa** [comment] 2020-07-15 17:41
This is not a file system issue - I've been able to replicate it when testing against a file on a ramdisk on the machine (`/dev/shm`)

**Comment by tmancill** [comment] 2020-07-15 18:20
> This is not a file system issue - I've been able to replicate it when testing against a file on a ramdisk on the machine (`/dev/shm`)

Is this possibly related to https://github.com/AdoptOpenJDK/openjdk-build/issues/1214?   That issue occurs on x86-64 and could be the same as [Debian #944738](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944738), where it cropped up ~8 months ago.  I haven't looked at it in any depth, it seems like it could be an issue with a common toolchain component.  The reporters of the Debian issue note that it doesn't occur with Oracle's builds.

**Comment by andrew-m-leonard** [comment] 2020-07-15 19:40
@tmancill @sxa #1214 maybe related, but fyi I have been able to replicate using a basic loop of sha256sum alone, and it fails very occaisionally on this particular machine, but works always on another machine...

**Comment by tmancill** [comment] 2020-07-15 20:18
@andrew-m-leonard Ah, in that case these sound like distinct issues.  Thanks!

**Comment by sxa** [comment] 2021-01-04 15:19
Similar issues are happening happening within docker images on the host. Attempting to upgrade to a later ubuntu may cause issues due to:
```
Leaving 'diversion of /etc/init/ureadahead.conf to /etc/init/ureadahead.conf.disabled by cloud-init'
Processing triggers for libc-bin (2.23-0ubuntu11.2) ...
Processing triggers for initramfs-tools (0.122ubuntu8.17) ...
update-initramfs: Generating /boot/initrd.img-4.10.0-26-generic
W: Possible missing firmware /lib/firmware/ast_dp501_fw.bin for module ast
W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
Unsupported platform on EFI system, doing nothing.
```
on an apt-get upgrade .. Hopefully this isn't a problem ...

**Comment by sxa** [comment] 2021-01-05 11:57
Sample errors seen on some of the test jobs on the same systems:
```
Receiving objects:  19% (2186/11502), 13.37 MiB | 13.37 MiB/s
Receiving objects:  20% (2301/11502), 13.37 MiB | 13.37 MiB/s
error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
or
```
Receiving objects:  12% (1381/11502)
error: RPC failed; curl 56 GnuTLS recv error (-12): A TLS fatal alert has been received.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Comment by sxa** [comment] 2021-01-05 15:46
OK ...

For now I have enabled the `dockerBuild` tag on [docker-packet-ubuntu1604-armv8-1](https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu1604-armv8-1/) (Not a ThunderX system) with three executors to see how it works - initial testing has shown that it's safe on those but we'll see ...

Separately I have enabled multiple docker containers under [build-packet-ubuntu1804-armv8l-1](https://ci.adoptopenjdk.net/computer/build-packet-ubuntu1804-armv8l-1/) (Five Ubuntu, four Fedora, all limited to use 8 of the 64-cores each) which are to be used for testing. I'll enable further distributions if this looks stable

**Comment by sxa** [comment] 2021-01-05 17:46
Ref OpenJ9 issue: https://github.com/eclipse/openj9/issues/9046

**Comment by sxa** [comment] 2021-02-05 17:15
Closing and will persue any subsequent remediation work we can identify under https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1897

**Closed by sxa** 2021-02-05 17:15 UTC
Labels: aarch, bug, openj9, x-linux

**Comment by tresf** [comment] 2022-08-03 22:44
Hi, I hope you don't mind me asking, but I'm experiencing this message attempting to use `jlink` in GitHub actions.  What's unobvious is:
1. Is there a workaround to keep jlink working?
2.  What's the cause?

In my case, I'm downloading Temurin from here: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12+7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz.

The issue only recently started cropping up, which leads me to believe that the GitHub environment is at fault (this same Temurin version is working locally).  GitHub Actions are using Temurin 11.0.16-8.

From what I'm reading there's a signature mismatch, but I don't entirely understand what that is and how an environment can recover from such a bug.

An example of a failed build is here: https://github.com/qzind/tray/runs/7662042575?check_suite_focus=true#step:5:354

**Comment by tresf** [comment] 2022-08-03 22:46
... a near identical Corretto issue: https://github.com/corretto/corretto-11/issues/144
