### ISSUE TITLE
OpenJ9 HealthCenter agent failed to start

### ISSUE THREAD

**Issue by Flandoll** [AdoptOpenJDK/openjdk-build#692] opened 2018-10-27 18:19 UTC
An error occurred while trying to use the `-Xhealthcenter` parameter on Windows

`PS D:\AdoptOpenJDK\jdk-11.0.1+13\bin> ./java -Xhealthcenter -version
JVMJ9TI001E 代理程序库 healthcenter 无法打开（找不到指定的模块。 ）
JVMJ9VM015W 在库 j9jvmti29(-3) 中发生初始化错误 JVMJ9VM009E J9VMDllMain 失败`

**Comment by sxa555** [comment] 2018-11-09 12:48
Thanks for raising this - the HealthCenter shared library is not currently included in the adoptopenjdk+openj9 builds which is why this is failing

**Comment by kgibm** [comment] 2019-03-25 20:46
For those wondering, eclipse/openj9#1538 notes that the HealthCenter agent was somehow installed into OpenJ9. I was able to get this to work (and also without `-Dsun.rmi.registry.registryFilter*`) using the following Dockerfile:

```
# usage:
# 1. Download agent using instructions at https://www.ibm.com/support/knowledgecenter/en/SS3KLZ/com.ibm.java.diagnostics.healthcenter.doc/topics/installingagent.html
# 2. Rename agent zip file as healthcenter.zip in the same directory as this Dockerfile
# 3. Build the Dockerfile
# 4. Run the Dockerfile and specify -Xhealthcenter* options

FROM adoptopenjdk/openjdk12-openj9:latest

LABEL maintainer="kevin.grigorenko@us.ibm.com"

RUN mkdir -p /opt/java/healthcenter/

COPY healthcenter.zip /opt/java/healthcenter/

RUN cd /opt/java/healthcenter/ && \
    jar xvf healthcenter.zip && \
    cp jre/lib/amd64/* /opt/java/openjdk/lib/ && \
    cp jre/lib/healthcenter.properties /opt/java/openjdk/lib/healthcenter.properties

ENV OPENJ9_JAVA_OPTIONS="-Xbootclasspath/a:/opt/java/healthcenter/jre/lib/ext/healthcenter.jar"
```

Running:

```
$ docker build -t adoptopenjdkopenj9healthcenter .
[...]
$ docker run adoptopenjdkopenj9healthcenter java -Xhealthcenter:level=headless -version
[Mon Mar 25 20:45:23 2019] com.ibm.diagnostics.healthcenter.headless INFO: 3.0.10
[Mon Mar 25 20:45:23 2019] com.ibm.diagnostics.healthcenter.headless INFO: Headless data collection has started
[Mon Mar 25 20:45:23 2019] com.ibm.diagnostics.healthcenter.headless INFO: Agent will keep last 5 hcd files
[Mon Mar 25 20:45:23 2019] com.ibm.diagnostics.healthcenter.headless INFO: Headless collection output directory is /
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment AdoptOpenJDK (build 12+33)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.13.0, JRE 12 Linux amd64-64-Bit Compressed References 20190320_41 (JIT enabled, AOT enabled)
OpenJ9   - caeb51f87
OMR      - 33a33ff2
JCL      - 419f571019 based on jdk-12+33)
[Mon Mar 25 20:45:23 2019] com.ibm.diagnostics.healthcenter.headless INFO: Creating hcd import file //healthcenter250319_204523_1_1.hcd
[Mon Mar 25 20:45:23 2019] com.ibm.diagnostics.healthcenter.headless INFO: hcd import file //healthcenter250319_204523_1_1.hcd created
```

FYI @pshipton

**Comment by pshipton** [comment] 2019-03-25 20:59
I suppose putting the healthcenter.jar on the bootclasspath avoided the need for `-Dsun.rmi.registry.registryFilter=javax.**`

**Comment by karianna** [comment] 2019-03-25 21:38
Is this an actual issue with the AdoptOpenJDK binary or the IBM HealthCenter product?

**Comment by kgibm** [comment] 2019-03-25 21:53
I'm not part of the Java team, so I'm not sure exactly how everything is scoped, but I believe the issue is that HealthCenter is not shipped with OpenJ9 as it is with IBM Java. The above is a workaround of downloading and placing HealthCenter into OpenJ9. As it stands, I don't think there's any technical issue with OpenJ9, but rather an open question of whether OpenJ9 will ship with the HealthCenter agent at some point. I believe there will be many customers that will be reluctant to move from IBM Java to OpenJ9 until HealthCenter is available.

**Comment by karianna** [comment] 2019-03-26 08:24
After checking with the OpenJ9 team this issue should be reported to the IBM health center project.  Closing here.

**Closed by karianna** 2019-03-26 08:24 UTC
Labels: bug, invalid, openj9

**Comment by sxa555** [comment] 2019-03-26 14:08
Also related (Health Center query)  https://github.com/AdoptOpenJDK/openjdk-docker/issues/104

**Comment by sxa555** [comment] 2020-01-24 17:58
Also (for anyone finding this issue @pshipton has these instructions https://github.com/eclipse/openj9/issues/1538#issuecomment-577894672
