### ISSUE TITLE
Microsoft Visual C++ Runtime Assertion Failed

### ISSUE THREAD

**Issue by linghuchong123** [AdoptOpenJDK/openjdk-build#760] opened 2018-11-22 17:47 UTC
I don't know what's going on, but something should happen! I hope it will be resolved soon

OpenJDK11U-jdk_x64_windows_openj9_jdk-11.0.1_13_openj9-0.11.0_11.0.1_13
Microsoft Visual C++ Runtime Assertion Failed

[screenshot is here](http://i1.bvimg.com/669744/92a81f6246239779.png)

**Comment by sxa555** [comment] 2018-11-22 19:11
Looks like it's somewhere in the OpenJ9 code, therefore have raised an issue against OpenJ9.

**Comment by sxa555** [comment] 2018-11-22 19:14
Actually I'll close that one as it's a duplicate of an existing OpenJ9 issue: https://github.com/eclipse/openj9/issues/3441

**Comment by linghuchong123** [comment] 2018-11-22 23:44
Ok

**Closed** 2018-11-23 04:09 UTC
Labels: bug, reported with upstream team

**Comment by linghuchong123** [comment] 2018-11-23 04:14
Thank you (^_^)
