### ISSUE TITLE
jdk15 build fails on osuosl-ppc64le-6 and osuosl-ppc64le-7 

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#2291] opened 2020-12-07 16:11 UTC
The jdk15 openj9 milestone 1 ppc64le and ppc64le_xl builds failed with:
```
12:07:57  /home/ubuntu/workspace/build-scripts/jobs/jdk15u/jdk15u-linux-ppc64le-openj9/sbin/build.sh: line 504: /bin/java: No such file or directory
```
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-ppc64le-openj9/135/console
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-ppc64le-openj9-linuxXL/143/console

**Comment by M-Davies** [comment] 2020-12-07 16:50
Warning in the script informs us of the failure (line [504 of build.sh](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L504))
```
12:07:03  [WARNING] Unable to find java to run gradle with, this build may fail with /bin/java: No such file or directory. Set JAVA_HOME, JDK8_BOOT_DIR or JDK11_BOOT_DIR to squash this warning: 
```

**Comment by Willsparker** [comment] 2020-12-08 10:08
I can't say I've even seen those machines before. I imagine they are temporarily provisioned ones? ping @gdams ; How are the those sorts of machines setup?

**Comment by Willsparker** [comment] 2020-12-08 11:27
Ah, this is a duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1707 . Closing this issue as I assume it's an infra problem, not a build problem.

**Closed by Willsparker** 2020-12-08 11:27 UTC
Labels: buildbreak, p-linux
