### ISSUE TITLE
Skip step sign when installer disabled

### ISSUE THREAD

**Issue by joeyleeeeeee97** [AdoptOpenJDK/openjdk-build#2231] opened 2020-11-16 09:06 UTC
All installer related jobs are private so we need to skip these steps when built on other Jenkins. So I propose we use "enableInstallers" to skip the signing step as well.
A failure example in ci.dragonwell : http://ci.dragonwell-jdk.io/view/build_scripts/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-dragonwell/48/

**Comment by M-Davies** [comment] 2020-11-16 16:37
Related / Close to being a duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/2160

**Closed** 2020-12-01 13:24 UTC
Labels: bug, duplicate, installer
