### ISSUE TITLE
cacerts is missing certificates

### ISSUE THREAD

**Issue by jwesselink** [AdoptOpenJDK/openjdk-build#1743] opened 2020-05-14 16:11 UTC
**Platform:**
linux-x64-openj9 (but possibly more images)

Hi!

It seems that that builds are missing some ca certificates. In my case i'm missing the "Staat der Nederlanden Root CA - G2" certificate.

Steps I did to verify:
* `docker run -it --rm adoptopenjdk/openjdk11-openj9:debianslim-jre bash`
* `cd /opt/java/openjdk/lib/security`
* `keytool -list -v -keystore cacerts | grep 'Owner:'`

The output from the keytook does not contain "Staat der Nederlanden Root CA - G2"

The `GenerateCertsFile.sh` script in the security folder of this repo is using https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt as source and that source does contain the "Staat der Nederlanden Root CA - G2" certificate

**Comment by aahlenst** [comment] 2020-05-14 16:18
Duplicate of https://github.com/AdoptOpenJDK/openjdk-support/issues/13. Fully analysis is in https://github.com/AdoptOpenJDK/openjdk-support/issues/13#issuecomment-626147267. We're going to work on it with OpenJDK.

**Closed by aahlenst** 2020-05-14 16:18 UTC
