### ISSUE TITLE
The lastest OpenJ9 releases for jdk8 and jdk11 are missing "_openj9-0.11.0"

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#678] opened 2018-10-22 16:45 UTC
The latest OpenJ9 release jdk8u192-b12 is missing the "_openj9-0.11.0" from the release name.
i.e. the earlier releases are "jdk8u162-b12_openj9-0.8.0" and "jdk8u181-b13_openj9-0.9.0" but the latest release is named "jdk8u192-b12"
https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9

The "_openj9-0.11.0" is also missing from the file names of all the downloads.

Its also missing for the jdk11 releases
https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=openj9

It was there for earlier jdk8 releases, and the Java 10 release
https://adoptopenjdk.net/archive.html?variant=openjdk10&jvmVariant=openj9

**Comment by karianna** [comment] 2018-10-22 19:55
Also reported as a website bug in https://github.com/AdoptOpenJDK/openjdk-website/issues/338

**Comment by sxa555** [comment] 2018-11-14 15:44
I'm going to close this one as a duplicate of the one in the website repo now that https://github.com/AdoptOpenJDK/openjdk-build/commit/8924f49e5b4cf3a9b8c0d0c5486dc44adce679f1 has gone in - the next builds (in progress at the moment will result in this being fixed.

**Closed by sxa555** 2018-11-14 15:44 UTC
Labels: bug
