### ISSUE TITLE
+ (plus sign) in the zip folder is not a good idea for windows

### ISSUE THREAD

**Issue by ca-stefan-cordes** [AdoptOpenJDK/openjdk-build#1154] opened 2019-07-10 12:52 UTC
Features that impact the whole project (e.g. Adding a new OpenJDK distribution)are made over at the [TSC](https://github.com/AdoptOpenJDK/TSC/).

Even the "+" sign is a valid file name it breaks e.g. automatic scripts with "copy" command:
* unzip OpenJDK11U-jdk_x64_windows_hotspot_11.0.3_7.zip
* copy jdk-11.0.3+7 jdk-11.0.3+7-original
=> fails with "The system cannot find the file specified."
as the "+" character is used for "concatination file names" in windows.

Please change it simply from jdk-11.0.3+7 to jdk-11.0.3-7 (like it is e.g. for the jdk8u212-b03 zips)

**Comment by karianna** [comment] 2019-07-10 13:09
A workaround is `copy "jdk-11.0.3+7 jdk-11.0.3+7-original"`

**Comment by ca-stefan-cordes** [comment] 2019-07-11 09:49
Thanks for workaround.
My workaround was to rename the folder in the Zip to jdk-11.0.3-7

**Comment by gdams** [comment] 2019-07-24 16:13
can this be closed?

**Comment by karianna** [comment] 2019-07-24 18:28
Probably not - I think we could make the Ux easier for the downloader here

**Comment by M-Davies** [comment] 2020-05-20 14:55
Also see https://github.com/AdoptOpenJDK/openjdk-build/issues/1016 for more discussions on renaming the binaries

**Comment by calle2010** [comment] 2020-08-24 18:19
Unfortunately the workaround with quotes doesn't work always very good in Windows, e. g. it fails when a wildcard is used:

MOVE "jdk*" "elsewhere"

returns "The filename, directory name, or volume label syntax is incorrect." in Windows 10.

**Comment by aahlenst** [comment] 2020-08-29 11:42
Duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/1016.

**Closed by aahlenst** 2020-08-29 11:42 UTC
Labels: bug
