### ISSUE TITLE
Smarter build process (recognising what's already present)

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#127] opened 2017-06-14 09:22 UTC
We pull in numerous dependencies e.g. alsa, freetype, and we even clone our repository again just to get cacerts out - every time!

Need to detect for the presence of such folders/files already and not do these steps all over again. Lost track of how many times I've said "oh no, it's configuring and building freetype again!"

**Comment by neomatrix369** [comment] 2017-06-14 15:59
I'm with you on this, we have already started via PR #117 and there's one more to follow, is it an idea to move some of them to the Ansible scripts so the machine already has them pre-baked. Also running cron jobs that update these dependencies regularly - might be useful to do this.

**Comment by karianna** [comment] 2018-12-10 16:34
Duplicate of #60

**Closed by karianna** 2018-12-10 16:34 UTC
Labels: bug, duplicate
