### ISSUE TITLE
java.base/java.io.ExpiringCache.cleanup java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jackjeyis** [AdoptOpenJDK/openjdk-build#2319] opened 2020-12-18 08:54 UTC
**What are you trying to do?**

**Expected behaviour:**

**Observed behaviour:**

**Any other comments:**

**Comment by jackjeyis** [comment] 2020-12-18 08:55
java.lang.ArrayIndexOutOfBoundsException: Index 255 out of bounds for length 255
	at java.base/java.io.ExpiringCache.cleanup(ExpiringCache.java:120)
	at java.base/java.io.ExpiringCache.get(ExpiringCache.java:76)
	at java.base/java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:158)
	at java.base/java.io.File.getCanonicalPath(File.java:618)
	at org.apache.catalina.webresources.AbstractFileResourceSet.file(AbstractFileResourceSet.java:90)
	at org.apache.catalina.webresources.DirResourceSet.getResource(DirResourceSet.java:101)
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2228)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:829)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1278)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1137)

**Comment by jackjeyis** [comment] 2020-12-18 08:57
Using CATALINA_BASE:   /opt/tomcat
Using CATALINA_HOME:   /opt/tomcat
Using CATALINA_TMPDIR: /opt/tomcat/temp
Using JRE_HOME:        /usr/java/jdk11
Using CLASSPATH:       /opt/tomcat/bin/bootstrap.jar:/opt/tomcat/bin/tomcat-juli.jar:/opt/tomcat/bin/ctrip-tomcat-patch-1.0.0.jar
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Server version: Apache Tomcat/8.5.32
Server built:   Jun 20 2018 19:50:35 UTC
Server number:  8.5.32.0
OS Name:        Linux
OS Version:     4.19.118-1.el7.centos.x86_64
Architecture:   amd64
JVM Version:    11.0.4+11
JVM Vendor:     AdoptOpenJDK

**Comment by aahlenst** [comment] 2020-12-18 10:36
Duplicate of https://github.com/AdoptOpenJDK/openjdk-support/issues/230.

**Closed by aahlenst** 2020-12-18 10:36 UTC

**Comment by rlodge** [comment] 2021-01-28 21:59
I understand this wasn't reproducible, but @jackjeyis did you get anywhere with it?
