### ISSUE TITLE
openjdk8-hotspot java version string can be improved

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#205] opened 2018-01-12 17:05 UTC
At present the adoptopenjdk builds for Java 8 print a version string that looks like this

```
$ ./java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2017_07_27_20_16-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)
$ ./java -fullversion
openjdk full version "1.8.0-internal-jenkins_2017_07_27_20_16-b00"
```

whereas other builders of similar code print like this
```
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
$ java -fullversion
java full version "1.8.0_151-b12"
```

We can use the configuration options to better identify the adoptopenjdk builds and make them more familiar to OpenJDK users.

See `configure` options, e.g.
```
  --with-milestone        Set milestone value for build [internal]
  --with-update-version   Set update version value for build [b00]
  --with-user-release-suffix
                          Add a custom string to the version string if build
                          number isn't set.[username_builddateb00]
  --with-build-number     Set build number value for build [b00]
```
used in [our build scripts here](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L110).

**Comment by karianna** [comment] 2018-01-12 18:28
Duplicate of #93 I think?

**Closed** 2019-01-10 15:08 UTC
Labels: duplicate, good first issue
