### ISSUE TITLE
apt-get update failing with a repository - Release file missing - error

### ISSUE THREAD

**Issue by teteich** [AdoptOpenJDK/openjdk-build#1904] opened 2020-06-17 13:59 UTC
**Platform:**
Docker

**Report:**

Similarly to this report: https://github.com/AdoptOpenJDK/openjdk-build/issues/1179
... we are seeing since today, 12:00p.m. UTC+1 that apt-get update is failing for AdoptOpenJDK with the following error:

adoptopenjdk_jfrog_io_adoptopenjdk_deb.list
15:22:53  -rw-r--r-- 1 root root   59 Aug 12  2019 download_docker_com_linux_ubuntu.list
15:22:53  -rw-r--r-- 1 root root  108 Jun 17 07:52 nodesource.list
15:22:53  *********
15:22:53  deb http://archive.ubuntu.com/ubuntu bionic main universe restricted
15:22:53  deb http://archive.ubuntu.com/ubuntu bionic-security main universe restricted
15:22:53  deb http://archive.ubuntu.com/ubuntu bionic-updates main universe restricted
15:22:53  *********
15:22:53  Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
15:22:53  Get:2 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
15:22:53  Hit:3 https://download.docker.com/linux/ubuntu bionic InRelease
15:22:54  Ign:4 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic InRelease
15:22:54  Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
15:22:54  Err:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic Release
15:22:54    Unknown date format Bad header data [IP: 35.231.52.82 443]
15:22:54  Hit:7 https://deb.nodesource.com/node_8.x bionic InRelease
15:22:57  Reading package lists...
15:22:58  E: The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic Release' no longer has a Release file.
15:22:58  [Pipeline] echo
15:22:58  Exception:java.io.IOException: Command returned status 100

Any help is appreciated.

**Comment by aahlenst** [comment] 2020-06-17 14:02
Duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1399.

**Closed by aahlenst** 2020-06-17 14:02 UTC
