### ISSUE TITLE
https://api.adoptopenjdk.net/openjdk8/releases web service not returning the latest AdoptOpenJDK8 binaries.

### ISSUE THREAD

**Issue by wfouche** [AdoptOpenJDK/openjdk-build#730] opened 2018-11-12 09:30 UTC
A call to https://api.adoptopenjdk.net/openjdk8/releases returns information for Java 8 (u172) instead of Java 8 (u192).

```
{
  "release_name": "jdk8u172-b11",
  "release_link": "https://github.com/AdoptOpenJDK/openjdk8-releases/releases/tag/jdk8u172-b11",
  "timestamp": "2018-05-19T11:14:21Z",
  "binaries": [
   {
      "platform": "Linux aarch64",
      "binary_name": "OpenJDK8_aarch64_Linux_jdk8u172-b11.tar.gz",
      "binary_link": "https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u172-b11/OpenJDK8_aarch64_Linux_jdk8u172-b11.tar.gz",
      "binary_size": "75 MB",
      "checksum_link": "https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u172-b11/OpenJDK8_aarch64_Linux_jdk8u172-b11.sha256.txt"
   },
   ...
   ...
   {
      "platform": "Windows x64",
      "binary_name": "OpenJDK8_x64_Win_jdk8u172-b11.zip",
      "binary_link": "https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u172-b11/OpenJDK8_x64_Win_jdk8u172-b11.zip",
      "binary_size": "73 MB",
      "checksum_link": "https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u172-b11/OpenJDK8_x64_Win_jdk8u172-b11.sha256.txt"
    }
  ]
}
```

**Comment by karianna** [comment] 2018-11-12 09:58
This is a duplicate of https://github.com/AdoptOpenJDK/openjdk-api/issues/124

**Closed by karianna** 2018-11-12 09:58 UTC
Labels: bug, duplicate
