### ISSUE TITLE
MacOS JDK/JRE 8 build with SDK older than 10.9

### ISSUE THREAD

**Issue by gamma** [AdoptOpenJDK/openjdk-build#1681] opened 2020-04-20 12:03 UTC
**Platform:**

MacOS

**Architecture:**

x64

The JDK/JRE is build with an SDK older than 10.9 which prohibits it from being notarised by Apple.

We have a product which uses the current JRE8 released by adopt. When notarising the App we receive the error from Apple for every binary (executable or dylib): "The binary uses an SDK older than the 10.9 SDK."

**Comment by aahlenst** [comment] 2020-04-20 12:17
Duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/1130. Read  https://github.com/AdoptOpenJDK/openjdk-build/issues/1130#issuecomment-611728413 for details. Should arrive soon.

**Closed by aahlenst** 2020-04-20 12:17 UTC
Labels: bug
