### ISSUE TITLE
Missing openj9 build for mac

### ISSUE THREAD

**Issue by bmhm** [AdoptOpenJDK/openjdk-build#683] opened 2018-10-23 09:16 UTC
Dear devs,

the macos openj9 build is [available for macos as a download](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9#x64_mac).
At least for JDK11.

I've seen closed source j9-jdk8 builds bundled with IBM Notes.

The matrix in the Readme.md file is missing macosx-openj9 alltogether.

Could you please look into, why:
* … why openj9 builds for jdk8 (and possibly jdk9/10) are missing?
* … why macosx-openj9 is missing in the build matrix, although it was build?

Thanks a lot!

**Comment by sxa555** [comment] 2018-10-23 09:40
I'm working on JDK8 (spent [most of yesterday on it](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/524) as it happens!) but there are some issues with the build process as they are introducing extra prereqs. There are no plans for any OpenJ9 builds with JDK9/JDK10 

The current builds can be downloaded from https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/ (They're not on the lightlies page yet) but as mentioned you might hit dependency issues (at a minimum it'll need `libstdc++` which you can probably get with `brew install gcc49`. If you try that install, let me know how it goes as I haven't checked that in a clean environment yet :-)

**Comment by ben-walsh** [comment] 2018-10-23 09:50
My Notes install on Mac doesn't appear to utilise any j9-jdk8 build ...
```
  501  1297     1   0 10:11am ??         3:02.45 /Applications/IBM Notes.app/Contents/MacOS/rcp/eclipse/plugins/com.ibm.rcp.base_9.0.2.20150831-1518/macosx/x86/eclipse --launcher.suppressErrors -nosplash -nl en_US -dir ltr -name IBM Notes -personality com.ibm.rcp.platform.personality -product com.ibm.rcp.personality.framework.RCPProduct:com.ibm.notes.branding.notes -data /Users/ben_walsh@uk.ibm.com/Library/Application Support/IBM Notes Data/Expeditor/Applications -configuration /Users/ben_walsh@uk.ibm.com/Library/Application Support/IBM Notes Data/Expeditor/Applications/.config -plugincustomization /Applications/IBM Notes.app/Contents/MacOS/rcp/plugin_customization.ini -vm /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -startup /Applications/IBM Notes.app/Contents/MacOS/rcp/eclipse/plugins/com.ibm.rcp.base_9.0.2.20150831-1518/launcher.jar -vmargs -Xdock:icon=/Applications/IBM Notes.app/Contents/Resources/appicon.icns -Djava.ext.dirs=/Applications/IBM Notes.app/Contents/MacOS/ndext:/Applications/IBM Notes.app/Contents/MacOS/jvm/lib/ext:/Library/Java/Extensions:/System/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin//Contents/Home/lib/ext -Dorg.eclipse.swt.internal.carbon.smallFonts -Xverify:none -XX:MaxPermSize=128M -Xmx256m -Xms48m -vm /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Djava.security.policy=/Applications/IBM Notes.app/Contents/MacOS/java.policy -Dorg.eclipse.swt.fixCitrix=false -XX:ErrorFile=/Users/ben_walsh@uk.ibm.com/Library/Application Support/IBM Notes Data/Expeditor/Applications/logs/java_error%p.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/ben_walsh@uk.ibm.com/Library/Application Support/IBM Notes Data/Expeditor/Applications/logs -Xverify:none -Xmx512m -Dosgi.framework.extensions=com.ibm.rcp.core.logger.frameworkhook -Drcp.home=/Applications/IBM Notes.app/Contents/MacOS -Drcp.data=/Users/ben_walsh@uk.ibm.com/Library/Application Support/IBM Notes Data/Expeditor/Applications -Dosgi.splashPath=platform:/base/../../shared/eclipse/plugins/com.ibm.notes.branding,platform:/base/../../shared/eclipse/plugins/com.ibm.notes.branding.nl1,platform:/base/../../shared/eclipse/plugins/com.ibm.notes.branding.nl2,platform:/base/../../shared/eclipse/plugins/com.ibm.notes.branding.nl3 -Dcom.ibm.rcp.install.id=1706182214 -Drcp.install.config=multiuser -Declipse.registry.nulltoken=true -Dcom.ibm.pvc.webcontainer.useLocalAddress=true -Dautopd.logfile.generations=3 -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeAwareParserConfiguration -Dcom.ibm.pvc.webcontainer.http.address=localhost -Dosgi.nl.user=true -Dautopd.instance.area=/Users/ben_walsh@uk.ibm.com/Library/Application Support/IBM Notes Data/Expeditor/Applications/autopd -Dorg.eclipse.swt.browser.XULRunnerPath=/Applications/IBM Notes.app/Contents/MacOS/rcp/eclipse/plugins/com.ibm.rcp.xulrunner.runtime.macosx.x86_64_9.0.2.20150831-1518/xulrunner -Djava.util.logging.config.class=com.ibm.rcp.core.internal.logger.boot.LoggerConfig -Dcom.ibm.pvc.webcontainer.port=0,59449 -Dcom.ibm.pvc.webcontainer.vhost.configfile=/Applications/IBM Notes.app/Contents/MacOS/shared/eclipse/plugins/com.ibm.collaboration.realtime.webapi_9.0.0.20150831-0324/virtualhost.properties -Dderby.stream.error.file=/Users/ben_walsh@uk.ibm.com/Library/Application Support/IBM Notes Data/Expeditor/Applications/logs/derby.log -Djava.security.properties=file:/Applications/IBM Notes.app/Contents/MacOS/rcp/eclipse/plugins/com.ibm.rcp.base_9.0.2.20150831-1518/rcp.security.properties -Dcom.lotus.sametime.skipRandomGeneratorSeed=true -Djava.protocol.handler.pkgs=com.ibm.net.ssl.www.protocol -Dosgi.hook.configurators.exclude=org.eclipse.core.runtime.internal.adaptor.EclipseLogHook -Drcp.osgi.install.area=/Applications/IBM Notes.app/Contents/MacOS/rcp/eclipse -Xbootclasspath/a:/Applications/IBM Notes.app/Contents/MacOS/shared/eclipse/plugins/com.ibm.collaboration.realtime.stjavatk_9.0.0.20150831-0324/sslite140-v3.16.jar:/Applications/IBM Notes.app/Contents/MacOS/rcp/eclipse/plugins/com.ibm.rcp.base_9.0.2.20150831-1518/rcpbootcp.jar -Dfile.encoding=UTF-8 -XstartOnFirstThread
```
```
bens-mbp:bin ben_walsh@uk.ibm.com$ "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java" -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by sxa555** [comment] 2018-10-23 13:03
@bmhm Ref your confused reaction on Ben's post - he was asking if you had the `java -version` output from the JVM you've seen in Notes, since we're not aware that there has been an IBM J9 VM on macos.

**Comment by bmhm** [comment] 2018-10-23 13:50
@sxa555 I was told it was Notes, but now I was told it might have been another IBM product which included a OpenJ9 JRE (no JDK). Sorry for the false information!

**Comment by sxa555** [comment] 2018-10-23 15:45
@bmhm No worries. To my knowledge there has never been a J9 on macos until this one :-)

**Comment by karianna** [comment] 2018-10-24 08:10
So this can be closed?

**Comment by planetf1** [comment] 2018-10-24 08:59
How do you want to track Java 8 J9 issues?
@sxa555 I just got this when doing a 'maven clean install' within IntelliJ idea on macOS with the J9 build. The regular adoptopenjdk openjdk hotspot builds (18x) are fine.

/Users/jonesn/java/jdk8u192-b12/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/jonesn/IdeaProjects/egeria -Dmaven.home=/Users/jonesn/IdeaProjects/maven/apache-maven-3.5.4 -Dclassworlds.conf=/Users/jonesn/IdeaProjects/maven/apache-maven-3.5.4/bin/m2.conf "-javaagent:/Users/jonesn/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/183.3795.13/IntelliJ IDEA 2018.3 EAP.app/Contents/lib/idea_rt.jar=54304:/Users/jonesn/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/183.3795.13/IntelliJ IDEA 2018.3 EAP.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Users/jonesn/IdeaProjects/maven/apache-maven-3.5.4/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2018.3 clean install
Assertion failed: (!"JVM_SocketShutdown() stubbed!"), function JVM_SocketShutdown, file j7vmi.c, line 2375.
JVMDUMP039I Processing dump event "abort", detail "" at 2018/10/24 09:57:11 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/jonesn/java/jdk8u192-b12/Contents/Home/bin/core.20181024.095711.12684.0001.dmp' in response to an event
[INFO] Scanning for projects...

**Comment by karianna** [comment] 2018-10-24 09:10
That looks like a VM crash to me and should be reported at the Eclipse OpenJ9 upstream project.  Reporting issues here initially is fine (in case it's an Adopt Binary issue).

**Comment by planetf1** [comment] 2018-10-24 10:12
Any thoughts @sxa555 - I know we've had some issues with libraries etc so I'm a little doubtful if it is just an upstream issue. Will try on windows shortly as a comparison

**Comment by sxa555** [comment] 2018-10-24 11:14
@planetf1 I'd definitely raise it at https://github.com/eclipse/openj9 ... Bear in mind that JDK8/J9/macos has so far undergone minimal testing, so this information will be useful to the OpenJ9 team whether it's a dependency issue or an underlying problem. Please link back to this issue once you raise it :-)

**Comment by sxa555** [comment] 2018-10-24 11:15
> Reporting issues here initially is fine (in case it's an Adopt Binary issue).

Indeed - plus it gives us awareness of it in case someone else reports it to us!

**Comment by planetf1** [comment] 2018-10-25 07:32
I went one step further in the build - this time to run some unit tests only to hit another core dump

[INFO] Surefire report directory: /Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/frameworks/open-connector-framework/target/surefire-reports
JVMDUMP010I System dump written to /Users/jonesn/java/jdk8u192-b12/Contents/Home/bin/core.20181025.082618.45081.0001.dmp
JVMDUMP032I JVM requested Java dump using '/Users/jonesn/java/jdk8u192-b12/Contents/Home/bin/javacore.20181025.082618.45081.0002.txt' in response to an event

This DOES NOT occur on windows (the previous one kinda-did) so it could be a mac or build regression?
[javacore.20181025.082618.45081.0002.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/2513789/javacore.20181025.082618.45081.0002.txt)

I've not opened a J9 issue for this one -- maybe worth seeing how the first is received.

How are tests running with the build? I'm thinking it's worth waiting until the build is deemed 'good'? THough if the feedback is helpful I can note other issues as I work on my project

**Comment by karianna** [comment] 2018-10-25 10:09
We run a full pipeline of tests on the builds, might be interesting to add your ones to that?  Is it an OSS project?

**Comment by gdams** [comment] 2019-03-20 20:49
looks like this was closed upstream at the j9 project. Closing

**Closed by gdams** 2019-03-20 20:49 UTC
Labels: Waiting on OP, enhancement
